### ISSUE TITLE
Cell selection

### ISSUE THREAD

**Issue by dylanmr** [mohuangx/SAVER#10]
Hello and thank you for this exciting tool! 

What sort of filtration would you recommend prior to running SAVER? Would you recommend a fairly stringent filtering of cells based on UMI, gene counts and mitochondrial content prior to running the imputation?

**Comment by mohuangx** [comment]
Thanks for the question. I think the filtering depends on the overall sequencing depth and quality of cells. I tend to look at mitochondrial content, library size, and genes expressed to filter out cells that are clear outliers. I don't think there's a hard and fast rule though but I tend to be more conservative with filtering.

**Comment by dylanmr** [comment]
Thanks for the information. Looking forward to testing the tool!

Dylan
