### ISSUE TITLE
Error while running SAVER

### ISSUE THREAD

**Issue by ravipatel4** [mohuangx/SAVER#11]
Hello,

First of all let me say this, I think your approach for accurate measurement of gene expression from scRNA-seq data seems promising. I am trying to give SAVER a try with my data generated on DropSeq. I get the following error when I try to run the pipeline on my data or on the sample data provided with the package (linnarsson).

```
> saver.adneo = saver(linnarsson, npred = 5)
3529 genes, 500 cells
Running SAVER with 1 worker(s)
Calculating predictions for 5 genes using 3529 genes and 500 cells...
Estimating finish time with 5 genes.
Error in summary.connection(connection) : invalid connection

```

 Can you please let me know how to fix this?

Thanks.
Ravi

**Comment by mohuangx** [comment]
Hi Ravi,

Thanks for trying out SAVER. Are you running it locally or on a server? Also, can you provide the session info?

I just installed the most recent version on a new local computer and was able to run it successfully:
```
> a <- saver(linnarsson, npred = 5)
3529 genes, 500 cells
Running SAVER with 1 worker(s)
Calculating predictions for 5 genes using 3529 genes and 500 cells...
Estimating finish time with 5 genes.
  |==============================================================================| 100%
Estimating remaining 3524 genes.
  |==============================================================================| 100%
Done!
> Sys.time()
[1] "2018-07-06 17:14:33 PDT"
```

Best,
Mo

**Comment by ravipatel4** [comment]
Hi Mo,

Sorry for the trouble. It seems like I had some packages already loaded that were causing that error, because when I started a new session, the code works fine.

Thank you for your time.

Best,
Ravi
