### ISSUE TITLE
Is SAVER output compatible with typical scRNAseq analyses

### ISSUE THREAD

**Issue by ravipatel4** [mohuangx/SAVER#13]
Hi,

I have been using SAVER on my 10X data, and it seems to be working pretty well. I have mostly been using SAVER estimates for clustering analysis in R in order to define clusters. As a next step, I am interested in performing more sophisticated analyses such as, dimensionality reduction, differential gene expression, pseudotime analysis, etc. I am wondering if SAVER estimates can be treated as raw read counts for analysis in other softwares such as Seurat or Monocle (for pseudotime analysis for instance)? Or would you recommend some sorts of modification/normalization of the estimates before going into Seurat or Monocle? Do you think the SAVER estimates also follow negative binomial distribution (assumption used in many scRNAseq software) same as raw read counts?

Thank you in anticipation of your help.

**Comment by mohuangx** [comment]
Hi, 

From our experience, using the SAVER estimates as the input to Seurat and Monocle produces pretty good results. We didn't perform any prior modification or normalization. 

There's no requirement in the SAVER method that the SAVER estimates will end up being negative binomial, but the negative binomial distribution is pretty flexible so I would imagine you could use the SAVER estimates in methods that assume a negative binomial distribution (unless they require integer counts). In addition, how much a method depends on the negative binomial distribution varies from method to method.

Let me know if you have any further questions.

Best,
Mo

**Comment by ravipatel4** [comment]
This is helpful. Thank you, Mo!

Best,
Ravi
