### ISSUE TITLE
Correlation cutoff to increase speed

### ISSUE THREAD

**Issue by zji90** [mohuangx/SAVER#15]
Hi,
I have been using saver and its performance is amazing. However it takes too much time to finish, making it less useful in some situations. I wonder whether one feature can be added to substantially increase the computational speed. When estimating the prior mean of gene A, other genes are used to predict the expression of gene A. Is it possible to set a correlation cutoff to only include genes that are highly correlated with gene A? The idea is essentially sure independence screening.
Thanks!

**Comment by mohuangx** [comment]
Thanks for the suggestion. We actually experimented with implementing sure independence screening. We discovered that although the first couple of genes that entered the model were the ones that were highly correlated with the response, the rest of the genes that entered had no pattern with the correlation, with some of them actually being among the least correlated. In addition, this varied from dataset to dataset so in the end, we decided not to implement such a feature. However, we have incorporated various approximations and correlation filtering, and are investigating additional ways to further increase the speed.
