### ISSUE TITLE
Error in cbind2(1, newx) : object 'newx' not found

### ISSUE THREAD

**Issue by mkywall** [mohuangx/SAVER#16]
I am getting this error when I try to run saver with the matrix of raw counts and a vector of size factors.  The  count matrix I am using is from an sce object.  I have tried using just the matrices produced by counts(sce_obj), as.matrix(counts(sce_obj)), and data.matrix(counts(sce_obj)).  The size factors I am using are the size factors computed by scran.  Any help would be greatly appreciated, thanks!

**Comment by mohuangx** [comment]
Could you copy and paste the command call that you used?
