### ISSUE TITLE
Error in UseMethod("units<-") :

### ISSUE THREAD

**Issue by joonlee3** [mohuangx/SAVER#17]
Hi,

   I kept receiving the following error message from SAVER. I am wondering what caused this problem. Would you please help me resolving this issue? Thanks.

**Estimating finish time...
Loading required package: SAVER
loaded SAVER and set parent environment
Loading required package: SAVER
loaded SAVER and set parent environment
Loading required package: SAVER
loaded SAVER and set parent environment
Loading required package: SAVER
loaded SAVER and set parent environment
Loading required package: SAVER
loaded SAVER and set parent environment
Loading required package: SAVER
loaded SAVER and set parent environment
Loading required package: SAVER
loaded SAVER and set parent environment
Loading required package: SAVER
loaded SAVER and set parent environment
Finished 8/2206 genes. Approximate finish time: 2018-10-18 19:50:05
Calculating max cor cutoff...
loaded SAVER and set parent environment
loaded SAVER and set parent environment
loaded SAVER and set parent environment
loaded SAVER and set parent environment
loaded SAVER and set parent environment
loaded SAVER and set parent environment
loaded SAVER and set parent environment
loaded SAVER and set parent environment
Error in UseMethod("units<-") :
  no applicable method for 'units<-' applied to an object of class "c('double', 'numeric')"**

Best,
Joon

**Comment by mohuangx** [comment]
Hi Joon,

Sorry about that. Try installing the latest development version and see if that works.

Mo
