### ISSUE TITLE
SAVER keeps crashing due to non-finite values

### ISSUE THREAD

**Issue by jamesrhowe** [mohuangx/SAVER#19]
Hello,

I am trying to incorporate SAVER into my sequencing workflow. However, I keep getting the following messages, culminating with an error: 

14515 genes, 3126 cells
Running SAVER with 1 worker(s)
Calculating predictions for 14515 genes using 0 genes and 3126 cells...
Start time: 2018-12-01 01:36:01
Estimating finish time...
Finished 8/14515 genes. Approximate finish time: 2018-12-01 01:36:17
Calculating max cor cutoff...
Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) : 
     NA/NaN/Inf in 'x'

However, I know this cannot be true, as these are the two prior lines:

q_array <- t(q_array)  
q_array[!is.finite(q_array)] <- 0
q_array <- saver(q_array)

Is there something I am missing, such as a transformation done by the program that induces these non-finite values? If it helps at all, I immediately precede the step with batch correction via mnnCorrect.

Thanks!

**Comment by mohuangx** [comment]
The issue could be due to the output of mnnCorrect. SAVER is designed to work with raw or normalized counts, which I'm not sure if that's what mnnCorrect produces. You could try running SAVER on the count matrices first and then run the SAVER results through mnnCorrect.

**Comment by jamesrhowe** [comment]
I did SAVER first and it worked. Thanks a bunch!
