### ISSUE TITLE
Difference in output while using all genes vs using pred.genes

### ISSUE THREAD

**Issue by ravipatel4** [mohuangx/SAVER#22]
Hello,

I have a huge matrix of scRNA data that I would need to break down into small matrix for it to work on my server with limited RAM, followed by `combine.saver` as is explained in SAVER manual. I wanted to make sure that the output is similar if I predict all genes at once verses if I predict only a set of genes per a SAVER run. For this I took another small scRNA dataset and ran SAVER with default value for `pred.genes`, ie. all genes, verses with 1:10 value for `pred.genes`, ie. predict only first 10 genes. The estimates are very similar for many genes as expected, but for few genes the correlation is as poor as pearson r=0.16. I was hoping to see very similar estimates for all genes irrespective of if I predicted all genes vs a set of genes. Is my assumption valid or there is more going on behind the scene that could explain the discrepancies between different methods? I have provided commands that I used below. Please let me know if I should change my analysis in any way. 

```
saver(data.fltrd, ncores=5)   # all genes
saver(data.fltrd, pred.genes = 1:10, pred.genes.only = TRUE, do.fast = FALSE, ncores=5) # only 10 genes
```

Thank you.

**Comment by mohuangx** [comment]
It is expected that the estimates will be similar whether you predict all genes or a subset. However, there are sources of randomness in the method which may cause slightly different results from run to run. What percentage of genes have low correlation (less than 0.5)?

Also, have you looked at the expression levels of the genes with low correlation between runs? I would imagine that the expression of these genes are relatively low, leading to some inconsistency in estimation across runs.
