### ISSUE TITLE
Input and Output

### ISSUE THREAD

**Issue by Winnie09** [mohuangx/SAVER#23]
Dear author,

Thanks for developing the software! I have a few questions but did not find clear answer from your paper:

1. is the input a count matrix?
2. is the output a count matrix? Has it been normalized by library size, or log2-transformed?

Thanks!

**Comment by mohuangx** [comment]
Yes, the input is a count matrix with genes along the rows and cells along the columns. The output is an expression matrix normalized by library size, but the column sums my not add to one (See issue #21).

You can find more information in the tutorial [here](https://mohuangx.github.io/SAVER/articles/saver-tutorial.html).
