### ISSUE TITLE
questions about prior variance optimization step

### ISSUE THREAD

**Issue by KangchengHou** [mohuangx/SAVER#25]
Hi Mo,

Thanks for developing the great software! I have a question about the marginal likelihood optimization procedure in your implementation. what's the purpose of this step?

https://github.com/mohuangx/SAVER/blob/23f8311f64c50e1fbb5a318da9700a1146d4da66/R/optimize_variance.R#L39-L55 

I didn't find references in the paper or supp materials. It would be great if you can illustrate more about this. Thanks!!

Best,
Kangcheng

**Comment by mohuangx** [comment]
Hi Kangcheng,

Thanks for your interest. 

For most genes, we can simply maximize the log-likelihood function to get `mle.a`. However, there are cases where the log-likelihood at `mle.a` is very close to the log-likelihood at `min.a`, the value of the log-likelihood at a small value of _a_. This leads to a right skewed function truncated at 0. We have found that treating the log-likelihood like a density function and setting _a_ to be the mean gives more stable results than taking the maximum in these cases. Thus, we sample from the likelihood function and take the average of the samples. In actuality, `sum(samp*loglik3)` would be more efficient at calculating this.

Let me know if you have any additional questions.

Mo

**Comment by KangchengHou** [comment]
Thanks for the quick response! these are really helpful. I have a few more questions:

1. Could you clarify what "stable" means? is that refering to that such averaging procedure results in better performance (e.g. higher correlations with the reference dataset)?
2. what kind of genes will benefit more from such averaging procedure? e.g., lower abundance?
3. Do you have intuition why such procedure (treating the likelihood function as density function and estimate the meean) works? are there any related references?
4. how is 0.5, 10 chosen? is that specific to the distribution of the dataset being processed?

Thanks again!!

Best,
Kangcheng

**Comment by mohuangx** [comment]
1. We didn't check to see if there was a difference between averaging and taking the maximum in performance but what I mean by more stable is that the variance estimates from averaging make more sense than taking the maximum. If the maximum _a_ is very close to zero, then each cell's posterior variance is very small. Averaging alleviates this issue.
2. I don't remember exactly for which genes this behavior occurs but my guess is that it happens to genes which have extreme values. This will result in better prediction from the Lasso, but might lead to an underestimate of the prior variance.
3. I don't recall if I saw this idea somewhere or whether I came up with it but I liken it to comparing taking the posterior mean vs taking the posterior mode.
4. 0.5 was chosen by looking at some of the problem genes and how their log-likelihood functions looked like. 10 was chosen to make sure the grid of points to be evaluated had a non-negligible density. So not really specific to the dataset.

Sorry for the vague answers. This was a while ago so I don't remember the exact details. Let me know if you have any additional questions.

**Comment by KangchengHou** [comment]
Thanks again for the quick and detailed response!
All these make a lot of sense to me. I want to confirm a few more things..

> This will result in better prediction from the Lasso, but might lead to an underestimate of the prior variance.

Is it saying that for some genes, the variance estimates happen to be very low (however, it does not reflect the ground truth, such low variance estimates could caused by random noise, etc.) So we take the mean of the likelihood density function rather than the mode. And if we just do the maximum likelihood estimate, **we will fit the data better**, however, this might lead to an underestimate of the prior variance (Compared to the ground truth, because we could be fitting noise)
Does these make sense?

> If the maximum a is very close to zero, then each cell's posterior variance is very small.

Is there possibilility that these cells' true variance are indeed very small? So it actually makes sense to just use maximum likelihood to find the best fit.

Thanks!!

**Comment by mohuangx** [comment]
> And if we just do the maximum likelihood estimate, we will fit the data better, however, this might lead to an underestimate of the prior variance (Compared to the ground truth, because we could be fitting noise)

Yes, that makes sense. We want to err on the side of caution and would rather our prior variance be conservative and large.
> Is there possibilility that these cells' true variance are indeed very small? So it actually makes sense to just use maximum likelihood to find the best fit.

This could be the case but it's hard to determine. My feeling is that inthe cases where the maximum likelihood estimate is different from the mean, the resulting variances are so extremely low that it is not likely to actually be true.

**Comment by KangchengHou** [comment]
Thanks a lot for the detailed explanations again! these are really helpful to me!
