### ISSUE TITLE
Error reading from connection

### ISSUE THREAD

**Issue by arielah** [mohuangx/SAVER#28]
Hi, I am new to running SAVER and I'm encountering the following error when I try to run on my local machine:

`
> sce_matrix <- assay(sce, "counts")
> dim(sce_matrix)
> sce_saver <- saver(sce_matrix, ncores = 6)
16326 genes, 9250 cells
starting worker pid=4723 on localhost:11445 at 19:13:06.473
starting worker pid=4724 on localhost:11445 at 19:13:06.480
starting worker pid=4721 on localhost:11445 at 19:13:06.484
starting worker pid=4725 on localhost:11445 at 19:13:06.487
starting worker pid=4722 on localhost:11445 at 19:13:06.490
starting worker pid=4726 on localhost:11445 at 19:13:06.493
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> -> workLoop -> makeSOCKmaster
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> -> workLoop -> makeSOCKmaster
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> -> workLoop -> makeSOCKmaster
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> -> workLoop -> makeSOCKmaster
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> -> workLoop -> makeSOCKmaster
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> -> workLoop -> makeSOCKmaster
Execution halted
Execution halted
Error in makePSOCKcluster(names = spec, ...) : 
  Cluster setup failed. 6 of 6 workers failed to connect.
`

Recommendations on how to address this? I get the same error when I try to run on the Zeisel cortex dataset used in the SAVER tutorial, so I don't think it has to do specifically with my dataset.

**Comment by mohuangx** [comment]
Hi, I did some searching and found this solution to the issue: https://github.com/rstudio/rstudio/issues/6692#issuecomment-619645114

Can you try running that before running saver and see if it fixes the issue?

**Comment by arielah** [comment]
That worked! Thank you for such a quick response.
