### ISSUE TITLE
Tutorial doesn't work

### ISSUE THREAD

**Issue by inoue0426** [mohuangx/SAVER#37]
Hi, 

I follow your tutorial (https://mohuangx.github.io/SAVER/articles/saver-tutorial.html#preprocessing). But it doesn't work.

This is my environment.

# Environment

```
# Ubuntu
$ lsb_release -d
Description:    Ubuntu 18.04.4 LTS

# R
R.version.string
'R version 4.2.0 (2022-04-22)'

# SAVER
library(SAVER)
packageVersion("SAVER")
[1] ‘1.1.2’
```

This is an error code.

# ERROR

```R
library(SAVER)
packageVersion("SAVER")
```

    [1] '1.1.2'

```R
data.path <- "expression_mRNA_17-Aug-2014.txt"

# Need to remove first 10 rows of metadata
raw.data <- read.table(data.path, header = FALSE, skip = 11, row.names = 1, 
                check.names = FALSE)
```

```R
head(raw.data)
```

<table class="dataframe">
<caption>A data.frame: 6 x 3006</caption>
<thead>
	<tr><th></th><th scope=col>V2</th><th scope=col>V3</th><th scope=col>V4</th><th scope=col>V5</th><th scope=col>V6</th><th scope=col>V7</th><th scope=col>V8</th><th scope=col>V9</th><th scope=col>V10</th><th scope=col>V11</th><th scope=col>...</th><th scope=col>V2998</th><th scope=col>V2999</th><th scope=col>V3000</th><th scope=col>V3001</th><th scope=col>V3002</th><th scope=col>V3003</th><th scope=col>V3004</th><th scope=col>V3005</th><th scope=col>V3006</th><th scope=col>V3007</th></tr>
	<tr><th></th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;int&gt;</th><th scope=col>...</th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;int&gt;</th></tr>
</thead>
<tbody>
	<tr><th scope=row>Tspan12</th><td>1</td><td>0</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>...</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td></tr>
	<tr><th scope=row>Tshz1</th><td>1</td><td>3</td><td>1</td><td>0</td><td>2</td><td>2</td><td>2</td><td>2</td><td>1</td><td>0</td><td>...</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td></tr>
	<tr><th scope=row>Fnbp1l</th><td>1</td><td>3</td><td>1</td><td>6</td><td>4</td><td>1</td><td>2</td><td>1</td><td>0</td><td>5</td><td>...</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
	<tr><th scope=row>Adamts15</th><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>...</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
	<tr><th scope=row>Cldn12</th><td>1</td><td>1</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>...</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
	<tr><th scope=row>Rxfp1</th><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>1</td><td>...</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
</tbody>
</table>

```R
cortex <- as.matrix(raw.data[, -1])
cellnames <- read.table(data.path, skip = 7, nrows = 1, row.names = 1, 
                        stringsAsFactors = FALSE)
colnames(cortex) <- cellnames[-1]
```

```R
head(cortex)
```

<table class="dataframe">
<caption>A matrix: 6 x 3005 of type int</caption>
<thead>
	<tr><th></th><th scope=col>1772071015_C02</th><th scope=col>1772071017_G12</th><th scope=col>1772071017_A05</th><th scope=col>1772071014_B06</th><th scope=col>1772067065_H06</th><th scope=col>1772071017_E02</th><th scope=col>1772067065_B07</th><th scope=col>1772067060_B09</th><th scope=col>1772071014_E04</th><th scope=col>1772071015_D04</th><th scope=col>...</th><th scope=col>1772066110_D12</th><th scope=col>1772071017_A07</th><th scope=col>1772063071_G10</th><th scope=col>1772058148_C03</th><th scope=col>1772063061_D09</th><th scope=col>1772067059_B04</th><th scope=col>1772066097_D04</th><th scope=col>1772063068_D01</th><th scope=col>1772066098_A12</th><th scope=col>1772058148_F03</th></tr>
</thead>
<tbody>
	<tr><th scope=row>Tspan12</th><td>0</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td>...</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td></tr>
	<tr><th scope=row>Tshz1</th><td>3</td><td>1</td><td>0</td><td>2</td><td>2</td><td>2</td><td>2</td><td>1</td><td>0</td><td>2</td><td>...</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td></tr>
	<tr><th scope=row>Fnbp1l</th><td>3</td><td>1</td><td>6</td><td>4</td><td>1</td><td>2</td><td>1</td><td>0</td><td>5</td><td>2</td><td>...</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
	<tr><th scope=row>Adamts15</th><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>...</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
	<tr><th scope=row>Cldn12</th><td>1</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>3</td><td>...</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
	<tr><th scope=row>Rxfp1</th><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>1</td><td>0</td><td>...</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
</tbody>
</table>

```R
dim(cortex)
```

```
19972 ･ 3005
```

```R
cortex.saver <- saver(cortex, ncores = 12)
```

    Error in if (!(grepl("matrix", class(x), ignore.case = TRUE))) {: the condition has length > 1
    Traceback:

    1. saver(cortex, ncores = 12)

    2. clean.data(x)

Do you know why this happens?

**Comment by mohuangx** [comment]
The issue was caused by R 4.2.0 updating the class of a matrix from just "matrix" to c("matrix", "array"). I fixed the issue in the latest Github version. Please install that version and see if you can run the tutorial.

**Comment by inoue0426** [comment]
@mohuangx Thank you for your quick reply!
I'll try it!

**Comment by inoue0426** [comment]
It works! Thank you for your help!
