### ISSUE TITLE
A bug detected

### ISSUE THREAD

**Issue by WT215** [mohuangx/SAVER#4]
Hi Mo,

SAVER is really cool!

I run it on a UMI count table but RStudio reported the following error (SAVER_0.3.1):

Calculating predictions for 9377 genes using 9375 genes and 74 cells...
Approximate finish time: 2018-02-19 10:29:56
Running in parallel: 5 workers
Error in out[[i]][lasso.genes, ] <- matrix(unlist(tempvec), nrow = length(tempvec),  : 
  number of items to replace is not a multiple of replacement length
In addition: Warning messages:
1: In get(object, envir = currentEnv, inherits = TRUE) :
  restarting interrupted promise evaluation
2: In get(object, envir = currentEnv, inherits = TRUE) :
  restarting interrupted promise evaluation
3: In get(object, envir = currentEnv, inherits = TRUE) :
  restarting interrupted promise evaluation
4: In get(object, envir = currentEnv, inherits = TRUE) :
  restarting interrupted promise evaluation
5: In doTryCatch(return(expr), name, parentenv, handler) :
  restarting interrupted promise evaluation
6: In doTryCatch(return(expr), name, parentenv, handler) :
  restarting interrupted promise evaluation
7: In doTryCatch(return(expr), name, parentenv, handler) :
  restarting interrupted promise evaluation
8: In doTryCatch(return(expr), name, parentenv, handler) :
  restarting interrupted promise evaluation
Timing stopped at: 11.72 1.1 1596

I think that this information "Error in out[[i]][lasso.genes, ] <- matrix(unlist(tempvec), nrow = length(tempvec),  : 
  number of items to replace is not a multiple of replacement length"  may be helpful.

I hope the above information is helpful.

Best wishes,
Wenhao

**Comment by WT215** [comment]
Hi Mo,

In saver, I set nzero=0, then saver can be run successfully.

Best wishes,
Wenhao

**Comment by mohuangx** [comment]
Hi Wenhao,

Thanks for bringing this to my attention. Can you provide the function call that you used?

Thanks,
Mo

**Comment by mohuangx** [comment]
Hi Wenhao,

We have just released a faster version of SAVER, which removes the code resulting in the error. Hope you can try it out!

Best,
Mo

**Comment by WT215** [comment]
Hi Mo,


Thank you very much! SAVER is very cool!


Best wishes,

Wenhao

________________________________
发件人: Mo Huang <notifications@github.com>
发送时间: 2018年3月1日 0:15:27
收件人: mohuangx/SAVER
抄送: Tang, Wenhao; Author
主题: Re: [mohuangx/SAVER] A bug detected (#4)


Hi Wenhao,

We have just released a faster version of SAVER, which removes the code resulting in the error. Hope you can try it out!

Best,
Mo

―
