### ISSUE TITLE
Error with R4.0+

### ISSUE THREAD

**Issue by danielgreenwood** [mohuangx/SAVER#41]
The saver function no longer works because of the following error:

```
> saver(matrix(1:9, nrow = 3))
Error in if (!(grepl("matrix", class(x), ignore.case = TRUE))) { : 
  the condition has length > 1
```

As far as I know, this is because the matrix class now inherits the array class too, so all matrices have two classes.

**Comment by mohuangx** [comment]
Hi,

Can you try installing the latest version from Github? 
See https://github.com/mohuangx/SAVER/issues/37

**Comment by danielgreenwood** [comment]
Thanks [mohuangx](https://github.com/mohuangx)! Yes the development version works.
